#+title: Readme
#+options: toc:nil ':t date:nil author:nil
* Checkpoint 5
** Preparations 
This notebook requires access to a private database server,
hence a file `src/regal_swans_private.py` is created
separately, where the reader is expected to replace the
value of `sql_pass` with the actual password, before
evaluating the work.

The jupyter notebook file is available as
`src/checkpoint5.ipynb`. One can either run `jupyter
notebook src/checkpoint5.ipynb` or upload this file *and*
`src/regal_swans_private.py` to Google Colab (or other
similar jupyter online services). There is no additional
dependencies other than the file containing the password.

#+begin_src python :exports source :exec never :eval nil :tangle src/regal_swans_private.py
# regal_swans_private.py
sql_pass = 'PUT_ACTUAL_PASSWORD_HERE'
sql_url = rf'postgresql://cpdbstudent:{sql_pass}@codd01.northwestern.edu/postgres'
#+end_src
** Part 1
Under the section "*Part 1*", a series of transformations take
place and the ultimate result is a scatter plot of years of
employment (experience) versus the allegation sentiment
score (severity). It is concluded that some insignificant
amount of correlation exists between experience and the
severity of allegation.
** Part 2
Under the section "*Part 2*", a series of transformations take
place and the ultimate result is a scatter plot of years of
employment (experience) versus the allegation sentiment
score (severity). It is condluded that virtually no
correlation exists between experience and the severity of a
lawsuit.
