#+title: Readme
#+options: toc:nil ':t date:nil author:nil
* Checkpoint 3
** Preparetions
#+begin_src markdown :exports none :eval never-export :tangle src/source.md
The URL for this checkpoint is available [[https://observablehq.com/d/89ea839fe3659e1e][here]].
#+end_src

# The URL for this checkpoint is available [[https://observablehq.com/d/89ea839fe3659e1e][here]].
The URL for this checkpoint is available [[https://observablehq.com/d/89ea839fe3659e1e][here]]. However,
since only private notebooks can have access to the
database, the audience should fork this notebook (to make it
a private notebook) and then add the CPDB data source under
the name "codd01". After the steps above, the plots should
be available.
** Part 1
Under the section "*Part 1*", there are two sets of radio
buttons -- weapon type and age group, respectively. Each set
of radio buttons controls the plot directly below these
buttons. 
** Part 2
Under the section "Part 2", there is a slide bar and a text
box, allowing the audience to either type the desired number
directly or use the slide bar to interactively put in the
desired years of employment. The graph below is the output.
